learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views



#TEMPLATE TAGGING
app_name='basic_app'      #tell django to look under basic_app and find the url that matches
                         


urlpatterns=[
    url(r'^basic/$',views.basic,name='basic'),
    url(r'^other/$',views.other,name='other'),
    url(r'^relative/$',views.relative,name='relative'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^basic_app/',include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict={'text':'hello world','number':100}
    return render(request,'basic_app/index.html',context=context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_template.html')

def basic(request):
    return render(request,'basic_app/basic.html')

learning_templates/templates/basic_app/basic.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>
     <div class="container">

       {% block body_block %}
       <!-- Anything outside of this will be inherited if u extend! -->
       {% endblock %}

     </div>


  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/basic.html" %}
{% load my_extras %}
  {% block body_block %}
    <h1>Welcome to index</h1>
    <h2>This is example of index.html page showing</h2>
    <h1>{{ text|cut:'world' }}</h1>     <!--cut is the custom filter defined under templatetags folder inside the basic_app folder-->
    <h1>{{ number|add:'99' }}</h1>
    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/basic.html" %}
  {% block body_block %}
    <h1>Welcome to other</h1>
    <h2>This is example of template inheritance</h2>
    {% endblock %}

learning_templates/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>RELATIVE URL TEMPLATE</title>
  </head>
  <body>
    <h1>Welcome to relative url template</h1>
    <a href="{% url 'basic_app:other' %}">link to OTHER</a>        
    <a href="{% url 'admin:index' %}">link to admin</a>
    <a href="{% url 'index' %}">link to index</a>
    <a href="{% url 'basic_app:basic' %}">link to BASIC</a>
    <a href="{% url 'basic_app:relative' %}">link to RELATIVE</a>
  </body>
</html>